[package]
name = "tooro-editor"
version = "0.1.0"
authors = ["Oliver Rockstedt <info@sourcebox.de>"]
edition = "2018"
description = "Töörö Editor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { git = "https://github.com/hecrj/iced.git", rev = "4b8ba8309f6645cdcb5bd605f8dd88097f8ee5a7", features=["tokio", "glow"]}
iced_native = { git = "https://github.com/hecrj/iced.git", rev = "4b8ba8309f6645cdcb5bd605f8dd88097f8ee5a7"}
iced_futures = { git = "https://github.com/hecrj/iced.git", rev = "4b8ba8309f6645cdcb5bd605f8dd88097f8ee5a7"}
midir = "0.7.0"
log = "0.4.14"
simple_logger = "1.11.0"
tinyfiledialogs = { git = "https://github.com/jdm/tinyfiledialogs-rs.git", rev = "83dea8cda8a6a9120765cf341883a6f2ada3fba5"}

[profile.release]
lto = true

[package.metadata.bundle]
name = "Töörö Editor"
identifier = "de.sourcebox.tooro-editor"
osx_minimum_system_version = "10.13"
