[package]
name = "tooro-editor"
version = "0.1.0"
authors = ["Oliver Rockstedt <info@sourcebox.de>"]
edition = "2018"
description = "Editor for the Fred's Lab Töörö hardware synthesizer"
repository = "https://github.com/sourcebox/tooro-editor"
license = "MIT"
keywords = ["midi", "synthesizer"]

[dependencies]
iced = { git = "https://github.com/hecrj/iced.git", rev = "d2c8a3e04b02a1fcf54504bcbd41c488a8bba88a", features=["tokio", "glow"]}
iced_native = { git = "https://github.com/hecrj/iced.git", rev = "d2c8a3e04b02a1fcf54504bcbd41c488a8bba88a"}
iced_futures = { git = "https://github.com/hecrj/iced.git", rev = "d2c8a3e04b02a1fcf54504bcbd41c488a8bba88a"}
midir = "0.7.0"
log = "0.4.14"
simple_logger = "1.11.0"
tinyfiledialogs = "3.8.3"

[profile.release]
lto = true

[package.metadata.bundle]
name = "Töörö Editor"
identifier = "de.sourcebox.tooro-editor"
osx_minimum_system_version = "10.11"
icon = ["icons/icon_32x32.png", "icons/icon_128x128.png", "icons/icon_256x256.png"]
