[package]
name = "tooro-editor"
version = "0.1.0"
authors = ["Oliver Rockstedt <info@sourcebox.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { git = "https://github.com/hecrj/iced.git", rev = "c1f70f1e9252b1971c17cd385273460c669fac26", features=["tokio", "glow"]}
midir = "0.7.0"

[profile.release]
lto = true
