[package]
name = "tooro-editor"
version = "1.2.0"
authors = ["Oliver Rockstedt <info@sourcebox.de>"]
edition = "2024"
rust-version = "1.92"
description = "Editor for the Fred's Lab Töörö hardware synthesizer"
repository = "https://github.com/sourcebox/tooro-editor"
license = "MIT"
keywords = ["midi", "synthesizer"]
publish = false

[features]
default = ["x11"]
x11 = ["iced/x11"]
wayland = ["iced/wayland"]
debug = ["iced/debug"]

[dependencies]
iced = { version = "0.14.0", default-features = false, features = ["advanced", "wgpu", "tokio"]}
midir = "0.11.0"
log = { version="0.4.33", features = ["max_level_debug", "release_max_level_warn"] }
simple_logger = "5.2.0"
num-traits = "0.2.19"
tinyfiledialogs = "3.9.1"
serde = { version = "1.0.228", features = ["derive"] }
ron = "0.12.2"
directories-next = "2.0.0"

[profile.release]
strip = true

[package.metadata.bundle]
name = "Töörö Editor"
identifier = "de.sourcebox.tooro-editor"
osx_minimum_system_version = "10.13"
icon = ["icons/icon_32x32.png", "icons/icon_128x128.png", "icons/icon_256x256.png"]
